# Detekt configuration
build:
  maxIssues: 10
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 1

auto-correct: true

processors:
  active: true
  exclude:
    - 'DetektProgressListener'
    - 'KtFileCountProcessor'
    - 'PackageCountProcessor'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'

style:
  active: true
  ForbiddenComment:
    active: true
    values: 'TODO:,FIXME:,STOPSHIP:'
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 200
  ReturnCount:
    active: true
    max: 8
    excludedFunctions: 'equals,toString,hashCode'
  WildcardImport:
    active: true

detekt:
  config:
    validation: true
    build:
      maxIssues: 10
    style:
      ReturnCount:
        active: true
        max: 8
    potential-bugs:
      UnreachableCode:
        active: true
    empty-blocks:
      active: true
    comments:
      active: true
    complexity:
      active: true
      LongMethod:
        active: true
        threshold: 60
      LongParameterList:
        active: true
        threshold: 6
      NestedBlockDepth:
        active: true
        threshold: 4
    performance:
      active: true
      ForEachOnRange:
        active: true
      SpreadOperator:
        active: true
      UnnecessaryTemporaryInstantiation:
        active: true
